# Generated by Django 4.1.7 on 2023-04-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('start_loc', models.CharField(max_length=100)),
                ('end_loc', models.CharField(max_length=100)),
                ('expiration_date', models.DateTimeField()),
                ('time_estimate', models.TimeField()),
            ],
        ),
    ]
